CC=g++
COMPILE_FLAGS=-Wall -Wextra -Werror -g -c
INC_DIRECTORY=inc
INCLUDE_FLAG=-I$(INC_DIRECTORY)
BUILD_DIRECTORY=build
OUTPUT_FILE=main
FLAGS=$(COMPILE_FLAGS) $(INCLUDE_FLAG)
COMPILE=$(CC) $(FLAGS)


# SOURCE FILES
MAIN_FILE=main.cpp

MODEL_DIRECTORY=Model
MODEL_FILES=Entity.cpp Car.cpp CarWash.cpp
COMPILE_MODEL_FILES=$(MODEL_FILES:%.cpp=$(MODEL_DIRECTORY)/%.cpp) 

SERVICE_DIRECTORY=Service
SERVICE_FILES=Service.cpp
COMPILE_SERVICE_FILES=$(SERVICE_FILES:%.cpp=$(SERVICE_DIRECTORY)/%.cpp) 

VIEW_DIRECTORY=View
VIEW_FILES=Console.cpp
COMPILE_VIEW_FILES=$(VIEW_FILES:%.cpp=$(VIEW_DIRECTORY)/%.cpp) 

OBJECTS=$(MODEL_FILES:%.cpp=%.o) $(SERVICE_FILES:%.cpp=%.o) $(VIEW_FILES:%.cpp=%.o) $(MAIN_FILE:%.cpp=%.o)

COMPILE_FILES=$(COMPILE_MODEL_FILES) $(COMPILE_SERVICE_FILES) $(COMPILE_VIEW_FILES) $(MAIN_FILE)

LINK=$(CC) $(OBJECTS) -o $(OUTPUT_FILE)


rebuild: clean_all build
build: build_objects link clean

build_objects:
	$(COMPILE) $(COMPILE_FILES) -c

link:
	$(LINK)
	
clean:
	rm -f $(OBJECTS)

clean_all:
	rm -f $(OBJECTS) 
	rm -f $(OUTPUT_FILE)